---
swagger: "2.0"
info:
  description: "Swagger for AWS-React project"
  version: "1.0.5"
  title: "AWS-React shop"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "https://h1l7nk2vf9.execute-api.us-east-1.amazonaws.com/dev"
basePath: "/v2"
tags:
- name: "products"
  description: "Products"
schemes:
- "https"
- "http"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Returns all products"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/product"
  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Returns product by id"
      description: "Returns product by id"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/product"

definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  Product:
    type: "object"
    required:
    - "price"
    - "title"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "Product title"
      price:
        type: "integer"
        example: 25.5
      description:
        type: "string"
        example: "Product description"
